# Generated by Django 2.1.3 on 2019-03-23 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=50)),
                ('mentor_description', models.CharField(max_length=250)),
                ('project_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_description', models.CharField(max_length=250)),
                ('project_id', models.IntegerField(default=0)),
                ('group_id', models.IntegerField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allot.Mentor')),
            ],
        ),
    ]
